{"name": "test_logout", "status": "broken", "statusDetails": {"message": "NameError: name 'y' is not defined", "trace": "self = <login_test.TestLogin object at 0x03B88B08>\n\n    def test_logout(self):\n>       y\nE       NameError: name 'y' is not defined\n\ntests\\login_test.py:27: NameError"}, "attachments": [{"name": "stdout", "source": "b28854b8-f9f1-4cd8-a3d6-9c7c64a21885-attachment.txt", "type": "text/plain"}], "start": 1593934196344, "stop": 1593934196344, "uuid": "184ba2b1-52ea-4d59-a29d-6df211051fa4", "historyId": "606d9f046945fff19ea92d7b1a10f16b", "testCaseId": "e89a5a0e9aefe451ee262eba82370b01", "fullName": "tests.login_test.TestLogin#test_logout", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('test_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-BFIIM5B"}, {"name": "thread", "value": "15372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}