{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: search_value() takes from 1 to 2 positional arguments but 3 were given", "trace": "self = <login_test.TestLogin object at 0x0421E178>\n\n    def test_login(self):\n        try:\n    \n            driver = self.driver\n            driver.get(utils.URL)\n    \n            login = LoginPage(driver)\n            homepage= HomePage(driver)\n            eventspage = EventsPage(driver)\n    \n            login.enter_username(utils.USERNAME)\n            login.enter_instance(utils.INSTANCE)\n            login.enter_password(utils.PASSWORD)\n            login.click_login()\n            homepage.navigate_events_screen()\n>           eventspage.search_value(self,\"NewUser\")\nE           TypeError: search_value() takes from 1 to 2 positional arguments but 3 were given\n\ntests\\login_test.py:32: TypeError"}, "attachments": [{"name": "test_login_05-07-2020_19-47-33", "source": "9f3242b0-4211-4a78-ac1a-2b1756d55be1-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "5dc7b674-a823-428c-accb-1b28243135c5-attachment.txt", "type": "text/plain"}], "start": 1593967642126, "stop": 1593967654613, "uuid": "5eb70862-5a98-4d2d-96f5-81d671974d88", "historyId": "8a9dfa4f406383cd388e6699ea6b6a72", "testCaseId": "2ce0d2b159a1b134adc13e328bfd71c0", "fullName": "tests.login_test.TestLogin#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('test_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-BFIIM5B"}, {"name": "thread", "value": "20384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}